# Basic Information 
title: Binesh Kumar
position: Ph.D Student
affiliation: SAIL Lab, University of New Haven
affiliation_link: https://sail-lab.org/
affiliation_logo: ./assets/img/logo.png
email: bsada1 (at) unh.newhaven.edu

# Search Engine Optimization (SEO)
keywords: Binesh Kumar, AI in Healthcare, Precision Oncology, Reinforcement Learning, Data Science
canonical: https://sail-lab.org/rushmore_teams/binesh-kumar/
description: Binesh Kumar, a second-year Ph.D. student at SAIL LAB, University of New Haven, focuses on the applications of AI in healthcare, particularly in reinforcement learning for precision oncology. With over 15 years of industry experience at Medtronic, he combines practical insights with academic research.

#
# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations
cv_link: assets/Binesh_Sadanandan_Resume.pdf
github_link: https://github.com/thedatasense
linkedin: https://www.linkedin.com/in/bineshk/
twitter: https://twitter.com/biny99

# Images 
avatar: https://media.licdn.com/dms/image/C4E03AQFfH1A8n-au2A/profile-displayphoto-shrink_400_400/0/1552013391623?e=1709769600&v=beta&t=X68WhFht3Gz2pIAA_gepf7fe1WLrNVW3eJQcK2v9jHk
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png


# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id:

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
